### ISSUE TITLE
Add project to Travis builder

### ISSUE THREAD

**Issue by bbottema** [pdorgambide/angular-logger#16]
Pablo, can you please add this project to [Travis](https://travis-ci.org/)? Just log in there using your GitHub account and turn on the knob for the angular-logger project. Only owners of the repository can do that, not collaborators.

I already added a Travis build manifest ".travis.yml" file to the root, which should be all Travis needs. When we get successful builds, we can add that as a flair badge to the home page.

**Comment by pdorgambide** [comment]
Done!! Thanks Benny

**Comment by bbottema** [comment]
The build is [currently failing](https://travis-ci.org/pdorgambide/angular-logger/builds/63294596). It seems Travis can't find the jasmine version we're using. Also, it's possible we will have to add an `npm install` and/or `bower install` command to the build manifest, but I'm not sure what Travis already does for us.

**Comment by bbottema** [comment]
Yay, we have a passing build! Awesome.
