### ISSUE TITLE
Use as default datetime stamp pattern the user's locale

### ISSUE THREAD

**Issue by pdorgambide** [pdorgambide/angular-logger#17]
Use as default datetime stamp patter the user locale. I think that the current does not fit well with regular used at development enviroments (e.g: Tomcat uses 08.11.2010 1:06:46). ;o)

**Comment by bbottema** [comment]
We can use the [localized formatting function](http://momentjs.com/docs/#localized-formats) for that. I suggest going for the second most verbose option, as the name of the day is not particularly interesting to developers.

``` javascript
app.config(function (logEnhancerProvider) {
   logEnhancerProvider.datetimePattern = 'LLL'; 
   // September 4 1986 8:30 PM, depending on current locale
});
```

However, momentjs will need locale information for that, which will make the momentjs dependency heavier, but that's up to the end-user.

Locale can globally be set from browser described below, but I don't want to do this in our code, potentially overriding the user's settings.

http://stackoverflow.com/questions/25725882/locale-detection-with-moment-js

`moment.locale(window.navigator.userLanguage || window.navigator.language);`

We can do this for every local moment instance, however.
