### ISSUE TITLE
Add Codacy oncommit-webhook to repo settings

### ISSUE THREAD

**Issue by bbottema** [pdorgambide/angular-logger#21]
Codacy can do an analyses on every commit, similarly to how Travis builds every commit and Code Climate and Coveralls is triggered every build.

From Codacy:

> **To setup the hook on GitHub**
> 
> Hook URL: _https://www.codacy.com/events/github/6cfb564bac114b54b26991575ea2eab4_
> 1. Copy the Hook URL to your clipboard
> 2. Go to "[Webhooks & Services](https://github.com/pdorgambide/angular-logger/settings/hooks/new)" under your repository settings
> 3. Paste the Hook URL into the "Payload URL" field
> 4. Select "application/json" in the "Content type" field
> 5. Click "Add webhook"

**Comment by pdorgambide** [comment]
Done !! thanks.

**Comment by bbottema** [comment]
Can you check the config once more? It doesn't seem to trigger updates in Codacy (it's not even pulling in new commits). Did you set it to "application/json" in the "Content type" field?

**Comment by bbottema** [comment]
It actually got triggered now... strangely so...
