### ISSUE TITLE
can I attach my own decorator to this?

### ISSUE THREAD

**Issue by edamon** [pdorgambide/angular-logger#24]
This is a pretty nice library, thanks!  I want to know if I can use a decorator to intercept the $log methods, because I want to allow for logging to an external source, like stacktracejs or trackjs.  Theoretically it should work, but it doesn't seem to be.

Edit:
I've figured out how to decorate the global $log.debug, $log.error, etc methods, but not sure how I can do it for specific $log.getInstance('string') objects.

**Comment by fdnhkj** [comment]
:+1:  
I was also looking for this, I would like to intercept the log messages.
I also tried to implement it by decorating $log (after angular-logger's decorator).
And indeed, it is possible for $log.info, $log.error, ... functions.

But it looks like it is not possible to decorate `getInstance` function.
I see in the code that `getInstance` function is defined in the run phase of the `angular-logger` module.
That's probably why we cannot decorate this function (as, AFAIK, decorator feature is only available in config phase).

**Comment by edamon** [comment]
Since the $log object is preserved in the `.$$orig$log` property, it is possible to still intercept the $log messages, but you can't do anything with the context provided to `GetInstance(context)` (like check it's logLevel), because it hasn't been created yet, and there's no way to get to it.

``` javascript
    $provide.decorator( '$log', [ '$delegate', function( $delegate )
    {
      // Save the original $log.debug()
      var nativeLog = $delegate.$$orig$log; //this is the original $log that logEnhancer replaced.
      var debugFn = $delegate.debug; //this is the logEnhancers drop in replacement for $log.  angular-logger config module ran first, so it has already put a decorator on $log

      function sendLogs( )
      {
        var levels = $delegate.LEVEL;    //this is the LEVELS object.
        var curLevel = $delegate.logLevels['*'];  //this is the levels set in the logEnhancerProvider

        var args    = [].slice.call(arguments);

        //you can do this for $log.debug, but not for $log.getInstance('foo').debug, because there's no way to get to the context
        //if (curLevel <= levels.DEBUG) {
          //send the log to some external persistance
          console.log(moment().toString() + ': do intercepty stuff: ', args);

          // Call the original with the output prepended with formatted timestamp
          debugFn.apply(null, args);
        //}
      };

      nativeLog.debug = sendLogs;
      $delegate.debug = sendLogs;
      return $delegate;
    }]);

    logEnhancerProvider.logLevel = { '*': logEnhancerProvider.LEVEL.TRACE };
```

**Comment by bbottema** [comment]
I will look into this somewhere this week (and move this issue over to https://github.com/better-js-logging/angular-logger).

**Comment by bbottema** [comment]
This issue was moved to better-js-logging/angular-logger#10
