### ISSUE TITLE
New feature to set loglevel per package/context/wildcard

### ISSUE THREAD

**Issue by bbottema** [pdorgambide/angular-logger#8]
We should have LogLevel support for packages, contexts and everything else.

Example contexts:

```
'MyService'
'myapp.mypackage.MyService'
'*'
```

These is a nesting here that determines the logging behavior, where more a specific context overrides a less specific context, with "*" being the least specific context.

Should be added in my upcoming Pull Request

**Comment by bbottema** [comment]
I added level priority and overriding, but I have not added the OFF level. I forgot that one. I'll add it after you merged this patch (if you haven't done so by then).

**Comment by bbottema** [comment]
Here's a jsfiddle I used to test to test level priority overrides with thresholds:

[jsFiddle](https://jsfiddle.net/plantface/0rddoL3b/)

``` javascript
this.LEVEL = { TRACE: 4, DEBUG: 3, INFO: 2, WARN: 1, ERROR: 0 };

var contexts = {
    'a.b.c': this.LEVEL.TRACE, // trace + debug + info + warn + error
    'a.b.d': this.LEVEL.ERROR, // error
    'a.b': this.LEVEL.DEBUG, // debug + info + warn + error
    'a': this.LEVEL.WARN, // warn + error
    '*': this.LEVEL.INFO // info + warn + error
};

function levelBelowThreshold(context, level) {
    return level <= getLogLevelThreshold(context);
}

function getLogLevelThreshold(context) {
    if (contexts[context]) {
        return contexts[context];
    } else if (context.indexOf('.') != -1) {
        return getLogLevelThreshold(context.substring(0, context.lastIndexOf('.')));
    } else {
        return contexts['*'];
    }
}

(...)
```

**Comment by bbottema** [comment]
Here's an example of setting the loglevels in your application:

``` javascript
app.
    .config(['logEnhancerProvider', function (logEnhancerProvider) {
            logEnhancerProvider.loggingPattern = '%s::[%s]> ';
            logEnhancerProvider.logLevels = {'*': logEnhancerProvider.LEVEL.TRACE};
            logEnhancerProvider.logLevels['myApp.myPackage.MyService'] = logEnhancerProvider.LEVEL.DEBUG;
            logEnhancerProvider.logLevels['myApp.myPackage'] = logEnhancerProvider.LEVEL.INFO;
            logEnhancerProvider.logLevels['myApp'] = logEnhancerProvider.LEVEL.WARN;
        }])
```

Alternatively entirely as object notation:

``` javascript
logEnhancerProvider.logLevels = {
    'myApp.myPackage.MyService': logEnhancerProvider.LEVEL.TRACE,
    'myApp.myPackage': logEnhancerProvider.LEVEL.DEBUG,
    'myApp': logEnhancerProvider.LEVEL.INFO,
    '*': logEnhancerProvider.LEVEL.WARN
};
```

**Comment by bbottema** [comment]
In addition to missing OFF logging level, I also didn't added a way to change loglevels after config phase. I suggest copying the `logLevels` from the provider into the return object from `.$get()`, which should from then on be used when logging instead of the provider one. 

The provider one is still useful however to configure initial log levels before the application is booted.

After this is added, we can start removing the `enableLogging` facility, as we can achieve the same by setting the log level for that context (or one its parent packages).

**Comment by bbottema** [comment]
Can you please add me as a collaborator, that make it a little easier. I think it makes sense, considering I made the initial version and I'm continuing development on it as well. I rather not continue as a separate fork.

https://github.com/pdorgambide/angular-logger/settings/collaboration

**Comment by pdorgambide** [comment]
Of course, as I put into the description your are the right father of the library. Thanks a lot for improve it ;o)
_Based on original post of: Enhancing $log in AngularJs the simple way by Benny Bottema_

**Comment by bbottema** [comment]
Ok, great!

**Comment by bbottema** [comment]
- Added the option to be able to change logLevels after config phase, by changing `$log.logLevels`.
- Added LEVEL.OFF for turning off a context completely ([jsFiddle](http://jsfiddle.net/plantface/e365cnxb/) for demo)
- Removed  `enabledContexts`
- Updated Readme.md

**Comment by bbottema** [comment]
Now for an OFF level and removing `enabledContexts`
